import express from 'express';
import taskController from './task.controller.js';
import { authenticate } from '../auth/auth.middleware.js';
import { requirePermission } from '../auth/permission.middleware.js';

const router = express.Router();

router.get('/', authenticate, taskController.getAll);
router.get('/active', authenticate, taskController.getActive);
router.get('/archived', authenticate, taskController.getArchived);
router.get('/overdue', authenticate, taskController.getOverdue);
router.get('/due-soon', authenticate, taskController.getDueSoon);
router.get('/statistics', authenticate, taskController.getStatistics);
router.get('/search', authenticate, taskController.search);
router.get('/project/:projectId', authenticate, taskController.getByProject);
router.get('/employee/:employeeId', authenticate, taskController.getByEmployee);
router.get('/department/:departmentId', authenticate, taskController.getByDepartment);
router.get('/employee/:employeeId/statistics', authenticate, taskController.getEmployeeStatistics);
router.get('/project/:projectId/statistics', authenticate, taskController.getProjectStatistics);
router.get('/status/:status', authenticate, taskController.getByStatus);
router.get('/priority/:priority', authenticate, taskController.getByPriority);
router.get('/category/:category', authenticate, taskController.getByCategory);
router.get('/parent/:parentTaskId', authenticate, taskController.getByParent);
router.get('/:id', authenticate, taskController.getById);
router.post('/', authenticate, requirePermission('task.create'), taskController.create);
router.patch('/:id', authenticate, requirePermission('task.update'), taskController.update);
router.delete('/:id', authenticate, requirePermission('task.delete'), taskController.delete);
router.patch('/restore/:id', authenticate, requirePermission('task.delete'), taskController.restore);
router.post('/:id/subtasks', authenticate, requirePermission('task.update'), taskController.addSubTask);
router.delete('/:id/subtasks', authenticate, requirePermission('task.update'), taskController.removeSubTask);
router.post('/:id/dependencies', authenticate, requirePermission('task.update'), taskController.addDependency);
router.delete('/:id/dependencies', authenticate, requirePermission('task.update'), taskController.removeDependency);
router.patch('/:id/archive', authenticate, requirePermission('task.update'), taskController.archive);
router.patch('/:id/unarchive', authenticate, requirePermission('task.update'), taskController.unarchive);
router.patch('/:id/progress', authenticate, requirePermission('task.update'), taskController.updateProgress);
router.patch('/:id/spent-hours', authenticate, requirePermission('task.update'), taskController.updateSpentHours);
router.patch('/:id/assign', authenticate, requirePermission('task.update'), taskController.assign);
router.patch('/:id/reassign', authenticate, requirePermission('task.update'), taskController.reassign);
router.post('/:id/assign-multiple', authenticate, requirePermission('task.update'), taskController.assignMultiple);
router.patch('/:id/assign-reviewer', authenticate, requirePermission('task.update'), taskController.assignReviewer);
router.patch('/:id/move', authenticate, requirePermission('task.update'), taskController.moveToProject);
router.post('/:id/clone', authenticate, requirePermission('task.create'), taskController.clone);
router.post('/:id/duplicate', authenticate, requirePermission('task.create'), taskController.duplicate);
router.patch('/:id/cancel', authenticate, requirePermission('task.update'), taskController.cancel);
router.patch('/:id/status', authenticate, requirePermission('task.update'), taskController.changeStatus);
router.patch('/:id/priority', authenticate, requirePermission('task.update'), taskController.changePriority);
router.patch('/:id/dependencies', authenticate, requirePermission('task.update'), taskController.addDependency);
router.delete('/:id/dependencies', authenticate, requirePermission('task.update'), taskController.removeDependency);
router.post('/:id/checklists', authenticate, requirePermission('task.update'), taskController.createChecklist);
router.patch('/checklists/:checklistId', authenticate, requirePermission('task.update'), taskController.updateChecklist);
router.delete('/checklists/:checklistId', authenticate, requirePermission('task.update'), taskController.deleteChecklist);
router.post('/:id/comments', authenticate, requirePermission('task.update'), taskController.addComment);
router.patch('/comments/:commentId', authenticate, requirePermission('task.update'), taskController.updateComment);
router.delete('/comments/:commentId', authenticate, requirePermission('task.update'), taskController.deleteComment);
router.get('/:id/timeline', authenticate, taskController.getTimeline);
router.post('/bulk/assign', authenticate, requirePermission('task.update'), taskController.bulkAssign);
router.post('/bulk/reassign', authenticate, requirePermission('task.update'), taskController.bulkReassign);
router.post('/bulk/archive', authenticate, requirePermission('task.update'), taskController.bulkArchive);
router.post('/bulk/delete', authenticate, requirePermission('task.delete'), taskController.bulkDelete);
router.post('/bulk/restore', authenticate, requirePermission('task.delete'), taskController.bulkRestore);
router.post('/bulk/status', authenticate, requirePermission('task.update'), taskController.bulkUpdateStatus);
router.post('/bulk/priority', authenticate, requirePermission('task.update'), taskController.bulkUpdatePriority);
router.post('/bulk/move', authenticate, requirePermission('task.update'), taskController.bulkMove);
router.post('/advanced-search', authenticate, taskController.advancedSearch);

export default router;
